ROLES = {
"ADMIN": "ADMIN",
"MANAGER": "MANAGER",
"STAFF": "STAFF",
"CUSTOMER": "CUSTOMER",
}


POD_STATUS = {
"AVAILABLE": "AVAILABLE",
"BUSY": "BUSY",
"MAINTAIN": "MAINTAIN",
}


BOOKING_STATUS = {
"PENDING": "PENDING",
"CONFIRMED": "CONFIRMED",
"CHECKED_IN": "CHECKED_IN",
"CHECKED_OUT": "CHECKED_OUT",
"CANCELLED": "CANCELLED",
}