ROLES = {"ADMIN": "ADMIN", "MANAGER": "MANAGER", "STAFF": "STAFF", "CUSTOMER": "CUSTOMER"}
BOOKING_STATUS = {"PENDING": "PENDING", "CONFIRMED": "CONFIRMED", "CHECKED_IN": "CHECKED_IN", "CHECKED_OUT": "CHECKED_OUT", "CANCELLED": "CANCELLED"}
POD_STATUS = {"AVAILABLE": "AVAILABLE", "BOOKED": "BOOKED"}
