@base = http://127.0.0.1:5000

### @name login
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "pbkdf2:sha256:260000$gipjvR1tIOaduXkq9wqDJw==$LwbZwaOYZs6ZOVhlj3lEsGHhtgJZNrsqtPfdVSSDQak="
}

### List PODs (tự dùng token từ request 'login')
GET {{base}}/pods/
Authorization: Bearer {{login.response.body.$.access_token}}

### Tạo booking (cũng tự dùng token từ 'login')
POST {{base}}/bookings/
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
  "pod_id": 1,
  "start_time": "2025-08-17T09:00:00",
  "end_time": "2025-08-17T11:00:00"
}
